### ISSUE TITLE
Viridian 5v line

### ISSUE THREAD

**Issue by ajaxharg** [delboy711/Solar_EVSE#1]
Hi,
I am making a charger in a similar manner to yourself but am using a photon and some custom software monitoring a solar edge inverter directly.  So many thanks for posting this resource which has been very helpful.

I have pulled apart the viridian and can't seem to see an obvious 5V point to take a power source from which you alluded to in the post.  Is it possible for you to give me a pointer to where that might be please.  Did you power up the device and just poke around with a multimeter?
Cheers
Andy

**Comment by delboy711** [comment]
Andy.
Take a look at the image viridian_evse1.jpg in the images folder of this repository. 5v is available on the expansion connector of the Viridian EVSE.  Unfortunately I failed to note down which pin it was and I used silicone goop to hold the wire in place which makes it harder to identify, but you will hopefully be able to find the correct pin.
Glad you found it useful.

Regards. derek

**Comment by ajaxharg** [comment]
Hi Derek
thanks for getting back to me.  I hadn't noticed the photos. Cheers for that. It seems mine is different to yours with a split board design with all the pins in use for the bridging.  There isn't much space to solder in.  The 12v line for the solenoid might get activated when the car is plugged in so I might try and use that.
Thanks
Andy
